# GitLab CI/CD конфигурация для Flask приложения
stages:
  - test
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/
    - venv/

# Тестирование
test:
  stage: test
  image: python:3.10
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - source venv/bin/activate
    - python -m pytest tests/ || echo "Тесты не найдены, пропускаем"
    - python -c "import app; print('✅ Приложение импортируется успешно')"
  only:
    - main
    - develop

# Сборка
build:
  stage: build
  image: python:3.10
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - source venv/bin/activate
    - echo "🔨 Сборка завершена"
    - echo "📦 Готов к деплою"
  artifacts:
    paths:
      - venv/
      - requirements.txt
      - app.py
      - static/
      - templates/
    expire_in: 1 hour
  only:
    - main
    - develop

# Деплой на сервер
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "🚀 Начинаем деплой на сервер..."
    - ssh $SSH_USER@$SSH_HOST "
        cd $DEPLOY_PATH &&
        git pull origin main &&
        source venv/bin/activate &&
        pip install -r requirements.txt &&
        sudo systemctl restart flask-app &&
        echo '✅ Деплой завершен успешно'
      "
  environment:
    name: production
    url: http://$SSH_HOST:5000
  only:
    - main
  when: manual 